# Generated by Django 4.2.1 on 2023-05-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_car_currency_car_description_car_total_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
