# Generated by Django 4.2.1 on 2023-05-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_alter_car_car_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vin_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
