# Generated by Django 4.2.1 on 2023-05-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_car_vin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year_made',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
