# Generated by Django 4.2.1 on 2023-05-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0006_remove_car_total_expense'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpensesModel',
            new_name='Expense',
        ),
    ]
