# Generated by Django 4.2.1 on 2023-05-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0007_rename_expensesmodel_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='year_made',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('PRT', 'Parts'), ('LBR', 'Labor'), ('MSC', 'Miscellaneous')], max_length=255),
        ),
    ]
